## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(Y5kjQIYvTB8hITXDsgZuSw==) #portal
      client-secret: ENC(xWZB6li8jOnobv6/kdmRBzvX2UUWeC3d) #sunshine
      scope: server
      #默认放行、服务间调用需要放行
      ignore-urls:
        - /actuator/**
        - /v2/api-docs
        - /we/chat/api/**
# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    username: micro_portal
    password: portal2019
    url: jdbc:oracle:thin:@micro-oracle:1521:orcl
  resources:
    static-locations: classpath:/static/,classpath:/views/

mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
  #定义全局 类型转换 包 BLOB 字段转 String、后续需要转换可继续添加
  type-handlers-package: com.cloud.common.data.handler

  #全局线程池配置(核心线程、最大线程、最大队列数、存活时间（S）)
thread-pool:
  corePoolSize: 10
  maxPoolSize: 20
  queueCapacity: 40
  aliveSeconds: 60

#统一用户接口信息
tyyh:
  accesskey: 4bdfba6dc01f4345916deae2e00af53d
  secretkey: a4bfae64eef949f1a288a2fcee014a8f
  orgurl: http://68.26.19.197:8380/dcuc/api/users.action
  userurl: http://68.26.19.197:8380/dcuc/api/users/id
  #政务微信登录信息  appId 为字符串、切记如果是数字 别把单引号丢了
wechat-api:
  a-code: acode
  app-id: '0000150'
  developer-id: qwc7ed6a6f60af4cc5a6908aec418cace6
  developer-key: ZjgxMzUwMzUtMTA4NC00ZjM0LTg2NjQtY2I5YzM1ODM5NmY3
  token-url: http://api3.apaas.ydjw.gd:8082/jwcgi/portal/api/jwsecurity!getToken.action
  user-info-url:  http://api3.apaas.ydjw.gd:8082/jwcgi/api/user!getUser.action

