## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(lcVc1Tvp3hco+CSU8r3iEQ==)
      client-secret: ENC(lcVc1Tvp3hco+CSU8r3iEQ==)
      scope: server
## 定时任务
spring:
  # 保存定时任务的数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ygnet
    password: sunshine@123
    url: jdbc:mysql://ygnet3306.mysql.rds.aliyuncs.com:3306/micro_upms?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
  elasticjob:
    # 分布式任务协调依赖zookeeper
    zookeeper:
      server-lists: micro-zookeeper:2181
      namespace: micro-daemon
    # 普通任务
    simples:
      spring-simple-job:
        job-class: com.cloud.daemon.job.MicroSimpleJob
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        eventTraceRdbDataSource: 'dataSource'
        listener:
          listener-class: com.cloud.daemon.listener.MicroElasticJobListener
      spring-simple-job2:
        job-class: com.cloud.daemon.job.MicroSimpleJob2
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        eventTraceRdbDataSource: 'dataSource'
        listener:
          listener-class: com.cloud.daemon.listener.MicroElasticJobListener
    # 简单任务
    dataflows:
      spring-dataflow-job:
        job-class: com.cloud.daemon.job.MicroDataflowJob
        cron: 0 0 0/1 * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=service1,1=service2,2=service3
        streaming-process: true
        eventTraceRdbDataSource: 'dataSource'
        listener:
          distributed-listener-class: com.cloud.daemon.listener.MicroDistributeElasticJobListener
          started-timeout-milliseconds: 5000
          completed-timeout-milliseconds: 10000
