## spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(XCTZhO/+DxaElFM72kSl+Q==)
      client-secret: ENC(XCTZhO/+DxaElFM72kSl+Q==)
      scope: server
# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ygnet
    password: sunshine@123
    url: jdbc:mysql://ygnet3306.mysql.rds.aliyuncs.com:3306/micro_portal?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
  resources:
    static-locations: classpath:/static/,classpath:/views/
